"""Write a readable sheet for reviewing the key facts: question, reference answer and facts together.

    python -m rag.observe.golden_tools.export_review

Output: data/golden/KEY_FACTS_REVIEW.md. Edit the key_facts in ddia_questions.jsonl, then rerun.
Check each fact against the reference answer: is it true, is it needed, and is it short enough to
be tested on its own? A fact that is wrong or too strict makes every answer to that question fail.
"""

from pathlib import Path

from rag.common.config import GOLDEN_DIR
from rag.observe.golden import load_golden


def main() -> None:
    questions = [q for q in load_golden(GOLDEN_DIR / "ddia_questions.jsonl") if q.answerable]
    lines = ["# Key facts review", "",
             "Generated by `python -m rag.observe.golden_tools.export_review`. An answer is correct only if it states "
             "every fact listed for its question.", ""]
    for q in questions:
        lines += [f"## {q.id} ({q.type}, PDF pages {', '.join(f'{a}-{b}' if a != b else str(a) for a, b in q.gold_pages)})",
                  "", f"**Question:** {q.question}", "", f"**Reference answer:** {q.reference_answer}", "",
                  "**Key facts:**"]
        lines += [f"{i}. {fact}" for i, fact in enumerate(q.key_facts, start=1)]
        lines.append("")
    out = GOLDEN_DIR / "KEY_FACTS_REVIEW.md"
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"{len(questions)} questions, {sum(len(q.key_facts) for q in questions)} facts -> {out}")


if __name__ == "__main__":
    main()
